
environment:
  matrix:
    - MINGW_DIR: C:\MinGW
      CMAKE_GENERATOR: "-G 'MinGW Makefiles'"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      DEVENV_EXE: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\Common7\IDE\devenv.exe
      VSDEVCMD_BAT: C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\Common7\Tools\VsDevCmd.bat
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      DEVENV_EXE: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\Common7\IDE\devenv.exe
      VSDEVCMD_BAT: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\Common7\Tools\VsDevCmd.bat

install:
  - set PATH=%PATH%;C:\MinGW\bin
  - if not exist deps mkdir deps
  - cd deps
  # zlib
  - curl -fsSL -o zlib.tar.gz https://github.com/madler/zlib/archive/v1.2.8.tar.gz
  - 7z x zlib.tar.gz -so | 7z x -si -ttar > nul
  - move zlib-1.2.8 zlib
  - cd zlib
  - cmake . "%CMAKE_GENERATOR%"
  - cmake --build .
  - cd ..
  # libPNG
  - curl -fsSL -o libpng.tar.gz http://prdownloads.sourceforge.net/libpng/libpng-1.6.28.tar.gz?download
  - 7z x libpng.tar.gz -so | 7z x -si -ttar > nul
  - move libpng-1.6.28 libpng
  - cd libpng
  - cmake . -DZLIB_INCLUDE_DIR=..\zlib -DZLIB_LIBRARY=..\zlib\debug\zlibstaticd.lib %CMAKE_GENERATOR%
  - cmake --build .
  - cd ..
  # go back to source root
  - cd ..

build_script:
  - mkdir build
  - cd build 
  - cmake --version
  - cmake .. -DZLIB_INCLUDE_DIR=..\deps\zlib -DZLIB_LIBRARY=..\deps\zlib\debug\zlibstaticd.lib -DPNG_PNG_INCLUDE_DIR=..\deps\libpng -DPNG_LIBRARY=..\deps\libpng\debug\libpng16_staticd.lib %CMAKE_GENERATOR%
  - cmake --build .
  - ctest -C Debug --output-on-failure


